
services:
  gateway-check:
    container_name: health_check
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app  # Bind mount for live development (optional)
    restart: unless-stopped
